package ar.com.mautech.ws.webservices.accionesseguridadomnichannel._1_0_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2017-05-16T15:59:10.707-03:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "AccionesSeguridadOmnichannel", 
                  wsdlLocation = "http://desaosb:8003/accionesseguridadomnichannel/anonimo?wsdl",
                  targetNamespace = "http://ws.mautech.com.ar/webservices/accionesseguridadomnichannel/1_0_0") 
public class AccionesSeguridadOmnichannel_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.mautech.com.ar/webservices/accionesseguridadomnichannel/1_0_0", "AccionesSeguridadOmnichannel");
    public final static QName AccionesSeguridadOmnichannel = new QName("http://ws.mautech.com.ar/webservices/accionesseguridadomnichannel/1_0_0", "AccionesSeguridadOmnichannel");
    static {
        URL url = null;
        try {
            url = new URL("http://desaosb:8003/accionesseguridadomnichannel/anonimo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AccionesSeguridadOmnichannel_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://desaosb:8003/accionesseguridadomnichannel/anonimo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AccionesSeguridadOmnichannel_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AccionesSeguridadOmnichannel_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccionesSeguridadOmnichannel_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AccionesSeguridadOmnichannel_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AccionesSeguridadOmnichannel_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AccionesSeguridadOmnichannel_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AccionesSeguridadOmnichannel
     */
    @WebEndpoint(name = "AccionesSeguridadOmnichannel")
    public AccionesSeguridadOmnichannel getAccionesSeguridadOmnichannel() {
        return super.getPort(AccionesSeguridadOmnichannel, AccionesSeguridadOmnichannel.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccionesSeguridadOmnichannel
     */
    @WebEndpoint(name = "AccionesSeguridadOmnichannel")
    public AccionesSeguridadOmnichannel getAccionesSeguridadOmnichannel(WebServiceFeature... features) {
        return super.getPort(AccionesSeguridadOmnichannel, AccionesSeguridadOmnichannel.class, features);
    }

}
