
package ar.com.mautech.ws.webservices.accionesseguridadomnichannel._1_0_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.11
 * 2017-05-16T15:59:10.698-03:00
 * Generated source version: 2.7.11
 */

@WebFault(name = "mtechResultadoOperacionFalla", targetNamespace = "http://ws.mautech.com.ar/webservices/globales/mtechresultadooperacion/2_0_0")
public class mtechResultadoOperacionFalla extends Exception {
    
    private ar.com.mautech.ws.webservices.globales.mtechresultadooperacion._2_0_0.mtechResultadoOperacionFalla mtechResultadoOperacionFalla;

    public mtechResultadoOperacionFalla() {
        super();
    }
    
    public mtechResultadoOperacionFalla(String message) {
        super(message);
    }
    
    public mtechResultadoOperacionFalla(String message, Throwable cause) {
        super(message, cause);
    }

    public mtechResultadoOperacionFalla(String message, ar.com.mautech.ws.webservices.globales.mtechresultadooperacion._2_0_0.mtechResultadoOperacionFalla mtechResultadoOperacionFalla) {
        super(message);
        this.mtechResultadoOperacionFalla = mtechResultadoOperacionFalla;
    }

    public mtechResultadoOperacionFalla(String message, ar.com.mautech.ws.webservices.globales.mtechresultadooperacion._2_0_0.mtechResultadoOperacionFalla mtechResultadoOperacionFalla, Throwable cause) {
        super(message, cause);
        this.mtechResultadoOperacionFalla = mtechResultadoOperacionFalla;
    }

    public ar.com.mautech.ws.webservices.globales.mtechresultadooperacion._2_0_0.mtechResultadoOperacionFalla getFaultInfo() {
        return this.mtechResultadoOperacionFalla;
    }
}
