
package ar.com.mautech.ws.webservices.accionescanalesalternativos._2_0_0;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2017-08-29T14:00:24.965-03:00
 * Generated source version: 2.7.11
 * 
 */
public final class AccionesCanalesAlternativos_AccionesCanalesAlternativos_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.mautech.com.ar/webservices/accionescanalesalternativos/2_0_0", "AccionesCanalesAlternativos");

    private AccionesCanalesAlternativos_AccionesCanalesAlternativos_Client() {
    }

//    public static void main(String args[]) throws java.lang.Exception {
//        URL wsdlURL = AccionesCanalesAlternativos_Service.WSDL_LOCATION;
//        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
//      
//        AccionesCanalesAlternativos_Service ss = new AccionesCanalesAlternativos_Service(wsdlURL, SERVICE_NAME);
//        AccionesCanalesAlternativos port = ss.getAccionesCanalesAlternativos();  
//        
//        {
//        System.out.println("Invoking loginClienteJuridicoConIdentificacion...");
//        ar.com.mautech.ws.webservices.accionescanalesalternativos.loginclientejuridicoconidentificacionrequest._2_0_0.LoginClienteJuridicoConIdentificacion _loginClienteJuridicoConIdentificacion_parameters = null;
//        try {
//            ar.com.mautech.ws.webservices.accionescanalesalternativos.loginclientejuridicoconidentificacionresponse._2_0_0.LoginClienteJuridicoConIdentificacionResult _loginClienteJuridicoConIdentificacion__return = port.loginClienteJuridicoConIdentificacion(_loginClienteJuridicoConIdentificacion_parameters);
//            System.out.println("loginClienteJuridicoConIdentificacion.result=" + _loginClienteJuridicoConIdentificacion__return);
//
//        } catch (mtechResultadoOperacionFalla e) {
//            System.out.println("Expected exception: mtechResultadoOperacionFalla has occurred.");
//            System.out.println(e.toString());
//        }
//            }
//        {
//        System.out.println("Invoking registrarAdhesionMetodoAutenticacion...");
//        ar.com.mautech.ws.webservices.accionescanalesalternativos.registraradhesionmetodoautenticacionrequest._1_0_0.RegistrarAdhesionMetodoAutenticacion _registrarAdhesionMetodoAutenticacion_parameters = null;
//        try {
//            ar.com.mautech.ws.webservices.accionescanalesalternativos.registraradhesionmetodoautenticacionresponse._1_0_0.RegistrarAdhesionMetodoAutenticacionResult _registrarAdhesionMetodoAutenticacion__return = port.registrarAdhesionMetodoAutenticacion(_registrarAdhesionMetodoAutenticacion_parameters);
//            System.out.println("registrarAdhesionMetodoAutenticacion.result=" + _registrarAdhesionMetodoAutenticacion__return);
//
//        } catch (mtechResultadoOperacionFalla e) {
//            System.out.println("Expected exception: mtechResultadoOperacionFalla has occurred.");
//            System.out.println(e.toString());
//        }
//            }
//        {
//        System.out.println("Invoking loginClienteSimplificado...");
//        ar.com.mautech.ws.webservices.accionescanalesalternativos.loginclientesimplificadorequest._1_0_0.LoginClienteSimplificado _loginClienteSimplificado_parameters = null;
//        try {
//            ar.com.mautech.ws.webservices.accionescanalesalternativos.loginclientesimplificadoresponse._1_0_0.LoginClienteSimplificadoResult _loginClienteSimplificado__return = port.loginClienteSimplificado(_loginClienteSimplificado_parameters);
//            System.out.println("loginClienteSimplificado.result=" + _loginClienteSimplificado__return);
//
//        } catch (mtechResultadoOperacionFalla e) {
//            System.out.println("Expected exception: mtechResultadoOperacionFalla has occurred.");
//            System.out.println(e.toString());
//        }
//            }
//        {
//        System.out.println("Invoking loginClienteFisicoConIdentificacion...");
//        ar.com.mautech.ws.webservices.accionescanalesalternativos.loginclientefisicoconidentificacionrequest._2_0_0.LoginClienteFisicoConIdentificacion _loginClienteFisicoConIdentificacion_parameters = null;
//        try {
//            ar.com.mautech.ws.webservices.accionescanalesalternativos.loginclientefisicoconidentificacionresponse._2_0_0.LoginClienteFisicoConIdentificacionResult _loginClienteFisicoConIdentificacion__return = port.loginClienteFisicoConIdentificacion(_loginClienteFisicoConIdentificacion_parameters);
//            System.out.println("loginClienteFisicoConIdentificacion.result=" + _loginClienteFisicoConIdentificacion__return);
//
//        } catch (mtechResultadoOperacionFalla e) {
//            System.out.println("Expected exception: mtechResultadoOperacionFalla has occurred.");
//            System.out.println(e.toString());
//        }
//            }
//        {
//        System.out.println("Invoking loginConTarjeta...");
//        ar.com.mautech.ws.webservices.accionescanalesalternativos.logincontarjetarequest._2_0_0.LoginConTarjeta _loginConTarjeta_parameters = null;
//        try {
//            ar.com.mautech.ws.webservices.accionescanalesalternativos.logincontarjetaresponse._2_0_0.LoginConTarjetaResult _loginConTarjeta__return = port.loginConTarjeta(_loginConTarjeta_parameters);
//            System.out.println("loginConTarjeta.result=" + _loginConTarjeta__return);
//
//        } catch (mtechResultadoOperacionFalla e) {
//            System.out.println("Expected exception: mtechResultadoOperacionFalla has occurred.");
//            System.out.println(e.toString());
//        }
//            }
//        {
//        System.out.println("Invoking registrarOperacionesMonetarias...");
//        ar.com.mautech.ws.webservices.accionescanalesalternativos.registraroperacionesmonetariasrequest._2_0_0.RegistrarOperacionesMonetarias _registrarOperacionesMonetarias_parameters = null;
//        try {
//            ar.com.mautech.ws.webservices.accionescanalesalternativos.registraroperacionesmonetariasresponse._2_0_0.RegistrarOperacionesMonetariasResult _registrarOperacionesMonetarias__return = port.registrarOperacionesMonetarias(_registrarOperacionesMonetarias_parameters);
//            System.out.println("registrarOperacionesMonetarias.result=" + _registrarOperacionesMonetarias__return);
//
//        } catch (mtechResultadoOperacionFalla e) {
//            System.out.println("Expected exception: mtechResultadoOperacionFalla has occurred.");
//            System.out.println(e.toString());
//        }
//            }
//        {
//        System.out.println("Invoking registrarInteracciones...");
//        ar.com.mautech.ws.webservices.accionescanalesalternativos.registrarinteraccionesrequest._2_0_0.RegistrarInteracciones _registrarInteracciones_parameters = null;
//        try {
//            ar.com.mautech.ws.webservices.accionescanalesalternativos.registrarinteraccionesresponse._2_0_0.RegistrarInteraccionesResult _registrarInteracciones__return = port.registrarInteracciones(_registrarInteracciones_parameters);
//            System.out.println("registrarInteracciones.result=" + _registrarInteracciones__return);
//
//        } catch (mtechResultadoOperacionFalla e) {
//            System.out.println("Expected exception: mtechResultadoOperacionFalla has occurred.");
//            System.out.println(e.toString());
//        }
//            }
//
//        System.exit(0);
//    }

}
